name: Publish to PyPI
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build
        - name: Build the package
          run: python -m build
        - name: Publish package to PyPI
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          run: |
            python -m pip install --upgrade twine
            twine upload dist/*
        - name: Verify package
          run: |
            sleep 3
            pip install telesm
            telesm talisman
            telesm --list
            telesm --random
            telesm --search tal
            telesm --delete talisman